server:
  port: 8090

spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8080/realms/spring/protocol/openid-connect/certs
            issuer-uri: http://localhost:8080/realms/spring
jwt:
  secret: some-32-character-ultra-secure-and-ultra-long-secret
  issuer: Exerimental development team
  type: JWT
  audience: SecurityApp
  expTime: 36000
  refreshExp: 48000

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
  show-actuator: true
